# Generated by Django 5.2.4 on 2025-07-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='preventive_measures',
            field=models.TextField(blank=True, null=True),
        ),
    ]
