remedies = {
    'Apple___Apple_scab': 'Remedy 1 for Apple___Apple_scab. Remedy 2 for Apple___Apple_scab. Remedy 3 for Apple___Apple_scab.',
    'Apple___Black_rot': 'Remedy 1 for Apple___Black_rot. Remedy 2 for Apple___Black_rot. Remedy 3 for Apple___Black_rot.',
    'Apple___Cedar_apple_rust': 'Remedy 1 for Apple___Cedar_apple_rust. Remedy 2 for Apple___Cedar_apple_rust. Remedy 3 for Apple___Cedar_apple_rust.',
    'Apple___healthy': 'Remedy 1 for Apple___healthy. Remedy 2 for Apple___healthy. Remedy 3 for Apple___healthy.',
    'Blueberry___healthy': 'Remedy 1 for Blueberry___healthy. Remedy 2 for Blueberry___healthy. Remedy 3 for Blueberry___healthy.',
    'Cherry_(including_sour)___Powdery_mildew': 'Remedy 1 for Cherry_(including_sour)___Powdery_mildew. Remedy 2 for Cherry_(including_sour)___Powdery_mildew. Remedy 3 for Cherry_(including_sour)___Powdery_mildew.',
    'Cherry_(including_sour)___healthy': 'Remedy 1 for Cherry_(including_sour)___healthy. Remedy 2 for Cherry_(including_sour)___healthy. Remedy 3 for Cherry_(including_sour)___healthy.',
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': 'Remedy 1 for Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot. Remedy 2 for Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot. Remedy 3 for Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot.',
    'Corn_(maize)___Common_rust_': 'Remedy 1 for Corn_(maize)___Common_rust_. Remedy 2 for Corn_(maize)___Common_rust_. Remedy 3 for Corn_(maize)___Common_rust_.',
    'Corn_(maize)___Northern_Leaf_Blight': 'Remedy 1 for Corn_(maize)___Northern_Leaf_Blight. Remedy 2 for Corn_(maize)___Northern_Leaf_Blight. Remedy 3 for Corn_(maize)___Northern_Leaf_Blight.',
    'Corn_(maize)___healthy': 'Remedy 1 for Corn_(maize)___healthy. Remedy 2 for Corn_(maize)___healthy. Remedy 3 for Corn_(maize)___healthy.',
    'Grape___Black_rot': 'Remedy 1 for Grape___Black_rot. Remedy 2 for Grape___Black_rot. Remedy 3 for Grape___Black_rot.',
    'Grape___Esca_(Black_Measles)': 'Remedy 1 for Grape___Esca_(Black_Measles). Remedy 2 for Grape___Esca_(Black_Measles). Remedy 3 for Grape___Esca_(Black_Measles).',
    'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': 'Remedy 1 for Grape___Leaf_blight_(Isariopsis_Leaf_Spot). Remedy 2 for Grape___Leaf_blight_(Isariopsis_Leaf_Spot). Remedy 3 for Grape___Leaf_blight_(Isariopsis_Leaf_Spot).',
    'Grape___healthy': 'Remedy 1 for Grape___healthy. Remedy 2 for Grape___healthy. Remedy 3 for Grape___healthy.',
    'Orange___Haunglongbing_(Citrus_greening)': 'Remedy 1 for Orange___Haunglongbing_(Citrus_greening). Remedy 2 for Orange___Haunglongbing_(Citrus_greening). Remedy 3 for Orange___Haunglongbing_(Citrus_greening).',
    'Peach___Bacterial_spot': 'Remedy 1 for Peach___Bacterial_spot. Remedy 2 for Peach___Bacterial_spot. Remedy 3 for Peach___Bacterial_spot.',
    'Peach___healthy': 'Remedy 1 for Peach___healthy. Remedy 2 for Peach___healthy. Remedy 3 for Peach___healthy.',
    'Pepper,_bell___Bacterial_spot': 'Remedy 1 for Pepper,_bell___Bacterial_spot. Remedy 2 for Pepper,_bell___Bacterial_spot. Remedy 3 for Pepper,_bell___Bacterial_spot.',
    'Pepper,_bell___healthy': 'Remedy 1 for Pepper,_bell___healthy. Remedy 2 for Pepper,_bell___healthy. Remedy 3 for Pepper,_bell___healthy.',
    'Potato___Early_blight': 'Remedy 1 for Potato___Early_blight. Remedy 2 for Potato___Early_blight. Remedy 3 for Potato___Early_blight.',
    'Potato___Late_blight': 'Remedy 1 for Potato___Late_blight. Remedy 2 for Potato___Late_blight. Remedy 3 for Potato___Late_blight.',
    'Potato___healthy': 'Remedy 1 for Potato___healthy. Remedy 2 for Potato___healthy. Remedy 3 for Potato___healthy.',
    'Raspberry___healthy': 'Remedy 1 for Raspberry___healthy. Remedy 2 for Raspberry___healthy. Remedy 3 for Raspberry___healthy.',
    'Soybean___healthy': 'Remedy 1 for Soybean___healthy. Remedy 2 for Soybean___healthy. Remedy 3 for Soybean___healthy.',
    'Squash___Powdery_mildew': 'Remedy 1 for Squash___Powdery_mildew. Remedy 2 for Squash___Powdery_mildew. Remedy 3 for Squash___Powdery_mildew.',
    'Strawberry___Leaf_scorch': 'Remedy 1 for Strawberry___Leaf_scorch. Remedy 2 for Strawberry___Leaf_scorch. Remedy 3 for Strawberry___Leaf_scorch.',
    'Strawberry___healthy': 'Remedy 1 for Strawberry___healthy. Remedy 2 for Strawberry___healthy. Remedy 3 for Strawberry___healthy.',
    'Tomato___Bacterial_spot': 'Remedy 1 for Tomato___Bacterial_spot. Remedy 2 for Tomato___Bacterial_spot. Remedy 3 for Tomato___Bacterial_spot.',
    'Tomato___Early_blight': 'Remedy 1 for Tomato___Early_blight. Remedy 2 for Tomato___Early_blight. Remedy 3 for Tomato___Early_blight.',
    'Tomato___Late_blight': 'Remedy 1 for Tomato___Late_blight. Remedy 2 for Tomato___Late_blight. Remedy 3 for Tomato___Late_blight.',
    'Tomato___Leaf_Mold': 'Remedy 1 for Tomato___Leaf_Mold. Remedy 2 for Tomato___Leaf_Mold. Remedy 3 for Tomato___Leaf_Mold.',
    'Tomato___Septoria_leaf_spot': 'Remedy 1 for Tomato___Septoria_leaf_spot. Remedy 2 for Tomato___Septoria_leaf_spot. Remedy 3 for Tomato___Septoria_leaf_spot.',
    'Tomato___Spider_mites Two-spotted_spider_mite': 'Remedy 1 for Tomato___Spider_mites Two-spotted_spider_mite. Remedy 2 for Tomato___Spider_mites Two-spotted_spider_mite. Remedy 3 for Tomato___Spider_mites Two-spotted_spider_mite.',
    'Tomato___Target_Spot': 'Remedy 1 for Tomato___Target_Spot. Remedy 2 for Tomato___Target_Spot. Remedy 3 for Tomato___Target_Spot.',
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus': 'Remedy 1 for Tomato___Tomato_Yellow_Leaf_Curl_Virus. Remedy 2 for Tomato___Tomato_Yellow_Leaf_Curl_Virus. Remedy 3 for Tomato___Tomato_Yellow_Leaf_Curl_Virus.',
    'Tomato___Tomato_mosaic_virus': 'Remedy 1 for Tomato___Tomato_mosaic_virus. Remedy 2 for Tomato___Tomato_mosaic_virus. Remedy 3 for Tomato___Tomato_mosaic_virus.',
    'Tomato___healthy': 'Remedy 1 for Tomato___healthy. Remedy 2 for Tomato___healthy. Remedy 3 for Tomato___healthy.',
}

preventive_measures = {
    'Apple___Apple_scab': 'Prevention 1 for Apple___Apple_scab. Prevention 2 for Apple___Apple_scab. Prevention 3 for Apple___Apple_scab.',
    'Apple___Black_rot': 'Prevention 1 for Apple___Black_rot. Prevention 2 for Apple___Black_rot. Prevention 3 for Apple___Black_rot.',
    'Apple___Cedar_apple_rust': 'Prevention 1 for Apple___Cedar_apple_rust. Prevention 2 for Apple___Cedar_apple_rust. Prevention 3 for Apple___Cedar_apple_rust.',
    'Apple___healthy': 'Prevention 1 for Apple___healthy. Prevention 2 for Apple___healthy. Prevention 3 for Apple___healthy.',
    'Blueberry___healthy': 'Prevention 1 for Blueberry___healthy. Prevention 2 for Blueberry___healthy. Prevention 3 for Blueberry___healthy.',
    'Cherry_(including_sour)___Powdery_mildew': 'Prevention 1 for Cherry_(including_sour)___Powdery_mildew. Prevention 2 for Cherry_(including_sour)___Powdery_mildew. Prevention 3 for Cherry_(including_sour)___Powdery_mildew.',
    'Cherry_(including_sour)___healthy': 'Prevention 1 for Cherry_(including_sour)___healthy. Prevention 2 for Cherry_(including_sour)___healthy. Prevention 3 for Cherry_(including_sour)___healthy.',
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': 'Prevention 1 for Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot. Prevention 2 for Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot. Prevention 3 for Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot.',
    'Corn_(maize)___Common_rust_': 'Prevention 1 for Corn_(maize)___Common_rust_. Prevention 2 for Corn_(maize)___Common_rust_. Prevention 3 for Corn_(maize)___Common_rust_.',
    'Corn_(maize)___Northern_Leaf_Blight': 'Prevention 1 for Corn_(maize)___Northern_Leaf_Blight. Prevention 2 for Corn_(maize)___Northern_Leaf_Blight. Prevention 3 for Corn_(maize)___Northern_Leaf_Blight.',
    'Corn_(maize)___healthy': 'Prevention 1 for Corn_(maize)___healthy. Prevention 2 for Corn_(maize)___healthy. Prevention 3 for Corn_(maize)___healthy.',
    'Grape___Black_rot': 'Prevention 1 for Grape___Black_rot. Prevention 2 for Grape___Black_rot. Prevention 3 for Grape___Black_rot.',
    'Grape___Esca_(Black_Measles)': 'Prevention 1 for Grape___Esca_(Black_Measles). Prevention 2 for Grape___Esca_(Black_Measles). Prevention 3 for Grape___Esca_(Black_Measles).',
    'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': 'Prevention 1 for Grape___Leaf_blight_(Isariopsis_Leaf_Spot). Prevention 2 for Grape___Leaf_blight_(Isariopsis_Leaf_Spot). Prevention 3 for Grape___Leaf_blight_(Isariopsis_Leaf_Spot).',
    'Grape___healthy': 'Prevention 1 for Grape___healthy. Prevention 2 for Grape___healthy. Prevention 3 for Grape___healthy.',
    'Orange___Haunglongbing_(Citrus_greening)': 'Prevention 1 for Orange___Haunglongbing_(Citrus_greening). Prevention 2 for Orange___Haunglongbing_(Citrus_greening). Prevention 3 for Orange___Haunglongbing_(Citrus_greening).',
    'Peach___Bacterial_spot': 'Prevention 1 for Peach___Bacterial_spot. Prevention 2 for Peach___Bacterial_spot. Prevention 3 for Peach___Bacterial_spot.',
    'Peach___healthy': 'Prevention 1 for Peach___healthy. Prevention 2 for Peach___healthy. Prevention 3 for Peach___healthy.',
    'Pepper,_bell___Bacterial_spot': 'Prevention 1 for Pepper,_bell___Bacterial_spot. Prevention 2 for Pepper,_bell___Bacterial_spot. Prevention 3 for Pepper,_bell___Bacterial_spot.',
    'Pepper,_bell___healthy': 'Prevention 1 for Pepper,_bell___healthy. Prevention 2 for Pepper,_bell___healthy. Prevention 3 for Pepper,_bell___healthy.',
    'Potato___Early_blight': 'Prevention 1 for Potato___Early_blight. Prevention 2 for Potato___Early_blight. Prevention 3 for Potato___Early_blight.',
    'Potato___Late_blight': 'Prevention 1 for Potato___Late_blight. Prevention 2 for Potato___Late_blight. Prevention 3 for Potato___Late_blight.',
    'Potato___healthy': 'Prevention 1 for Potato___healthy. Prevention 2 for Potato___healthy. Prevention 3 for Potato___healthy.',
    'Raspberry___healthy': 'Prevention 1 for Raspberry___healthy. Prevention 2 for Raspberry___healthy. Prevention 3 for Raspberry___healthy.',
    'Soybean___healthy': 'Prevention 1 for Soybean___healthy. Prevention 2 for Soybean___healthy. Prevention 3 for Soybean___healthy.',
    'Squash___Powdery_mildew': 'Prevention 1 for Squash___Powdery_mildew. Prevention 2 for Squash___Powdery_mildew. Prevention 3 for Squash___Powdery_mildew.',
    'Strawberry___Leaf_scorch': 'Prevention 1 for Strawberry___Leaf_scorch. Prevention 2 for Strawberry___Leaf_scorch. Prevention 3 for Strawberry___Leaf_scorch.',
    'Strawberry___healthy': 'Prevention 1 for Strawberry___healthy. Prevention 2 for Strawberry___healthy. Prevention 3 for Strawberry___healthy.',
    'Tomato___Bacterial_spot': 'Prevention 1 for Tomato___Bacterial_spot. Prevention 2 for Tomato___Bacterial_spot. Prevention 3 for Tomato___Bacterial_spot.',
    'Tomato___Early_blight': 'Prevention 1 for Tomato___Early_blight. Prevention 2 for Tomato___Early_blight. Prevention 3 for Tomato___Early_blight.',
    'Tomato___Late_blight': 'Prevention 1 for Tomato___Late_blight. Prevention 2 for Tomato___Late_blight. Prevention 3 for Tomato___Late_blight.',
    'Tomato___Leaf_Mold': 'Prevention 1 for Tomato___Leaf_Mold. Prevention 2 for Tomato___Leaf_Mold. Prevention 3 for Tomato___Leaf_Mold.',
    'Tomato___Septoria_leaf_spot': 'Prevention 1 for Tomato___Septoria_leaf_spot. Prevention 2 for Tomato___Septoria_leaf_spot. Prevention 3 for Tomato___Septoria_leaf_spot.',
    'Tomato___Spider_mites Two-spotted_spider_mite': 'Prevention 1 for Tomato___Spider_mites Two-spotted_spider_mite. Prevention 2 for Tomato___Spider_mites Two-spotted_spider_mite. Prevention 3 for Tomato___Spider_mites Two-spotted_spider_mite.',
    'Tomato___Target_Spot': 'Prevention 1 for Tomato___Target_Spot. Prevention 2 for Tomato___Target_Spot. Prevention 3 for Tomato___Target_Spot.',
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus': 'Prevention 1 for Tomato___Tomato_Yellow_Leaf_Curl_Virus. Prevention 2 for Tomato___Tomato_Yellow_Leaf_Curl_Virus. Prevention 3 for Tomato___Tomato_Yellow_Leaf_Curl_Virus.',
    'Tomato___Tomato_mosaic_virus': 'Prevention 1 for Tomato___Tomato_mosaic_virus. Prevention 2 for Tomato___Tomato_mosaic_virus. Prevention 3 for Tomato___Tomato_mosaic_virus.',
    'Tomato___healthy': 'Prevention 1 for Tomato___healthy. Prevention 2 for Tomato___healthy. Prevention 3 for Tomato___healthy.',
}